"""生成完全虚构的中文清单；图片已提交，不需要下载字体才能运行演示。"""
import json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, ImageFilter, ImageEnhance

ROOT = Path(__file__).resolve().parents[1]
TEXTS = ['星河文具采购清单', '仅用于识别演示', '单号 DEMO-1001', '日期 2026-09-28',
         '水性笔 3盒 12.00元', '笔记本 2本 18.00元', '文件夹 1个 8.50元',
         '合计 38.50元', '请核对数量与金额']


def make(size=34):
    # 只使用系统已安装字体绘制原创文字，不分发字体文件。
    path = Path('C:/Windows/Fonts/msyh.ttc')
    if not path.exists():
        raise RuntimeError('重新生成中文样例需要微软雅黑字体；现有samples可直接使用')
    font = ImageFont.truetype(str(path), size)
    image = Image.new('RGB',(900,900),'white')
    draw = ImageDraw.Draw(image)
    draw.rectangle((32,32,868,868),outline='#b7c7c2',width=2)
    for i,text in enumerate(TEXTS):
        draw.text((72,68+i*84),text,font=font,fill='#172e27')
    return image


def main():
    folder=ROOT/'samples';folder.mkdir(exist_ok=True)
    base=make()
    variants={'clean':base,'dim':ImageEnhance.Brightness(base).enhance(.55),
              'rotated':base.rotate(4,fillcolor='white',resample=Image.Resampling.BICUBIC),
              'blurred':base.filter(ImageFilter.GaussianBlur(1.5)),
              'tiny':base.resize((180,180),Image.Resampling.LANCZOS),
              'blank':Image.new('RGB',(900,900),'white')}
    for name,im in variants.items():im.save(folder/f'{name}.png')
    (folder/'ground-truth.json').write_text(json.dumps({'texts':TEXTS,'conditions':list(variants),
        'license':'Original synthetic sample, no personal information; generated by app/samples.py'},ensure_ascii=False,indent=2),encoding='utf-8')


if __name__=='__main__':main()
